package com.moneydance.modules.features.reportwriter2;

import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.events.XMLEvent;

import com.moneydance.modules.features.reportwriter2.view.controls.ReportTemplate;

public interface XmlWriter {
	public static final String TEMPLATE = "template";
	public static final String NAME ="name";
	public static final String TITLE ="title";
	public static final String PAGEHEADER ="pageheader";
	public static final String COLUMNHEADER ="columnheader";
	public static final String GROUPHEADER ="groupheader";
	public static final String DETAIL ="detail";
	public static final String GROUPFOOTER ="groupfooter";
	public static final String COLUMNFOOTER ="columnfooter";
	public static final String PAGEFOOTER ="pagefooter";
	public static final String ENDPAGE ="endpage";
	public static final String SELECTEDFIELDS ="selectedfields";
	public static final String QUESTION1="question1";
	public static final String QUESTION2="question2";
	public static final String QUESTION3="question3";
	public static final String QUESTION4="question4";
	public static final String FONTNAME="fontname";
	public static final String FONTWEIGHT="fontweight";
	public static final String FONTSIZE="fontsize";
	public static final String FONTITALIC="fontitalic";
	public static final String FONTUNDERLINE="fontunderline";
	public static final String SELFIELD ="selectfield";
	public static final String FIELDKEY ="fieldkey";
	public static final String DATASET ="dataset";
	public static final String DATASQL ="datasql";
	public static final String PAPERSIZE ="papersize";
	public static final String PAGELAYOUT ="pagelayout";
	public static final String LEFTMARGIN ="leftmargin";
	public static final String RIGHTMARGIN ="rightmargin";
	public static final String TOPMARGIN ="topmargin";
	public static final String BOTTOMMARGIN ="bottommargin";
	public static final String BANNERS="banners";
	public static final String BANNER="banner";
	public static final String BANNERTYPE="bannertype";
	public static final String BANNERSTYLE="bannerstyle";
	public static final String BANNERGROUPFIELD="bannergroupfield";
	public static final String CANVASWIDTH="canvaswidth";
	public static final String BANNERHEIGHT="pageheight";
	public static final String BANNERNEWPAGE="bannernewpage";
	public static final String BANNERREPEAT="bannerrepeat";
	public static final String BANNERTOPLINE="bannertopline";
	public static final String BANNERBOTTOMLINE="bannerbottomline";
	public static final String BANNERHASFOOTER="bannerhasfooter";
	public static final String BANNEROTHERPOS="bannerotherpos";	
	public static final String BANNERVISIBLE="bannervisible";	
	public static final String LABELS="labels";
	public static final String LABEL="label";
	public static final String LAYOUTFIELDS="layoutfields";
	public static final String LAYOUTFIELD="layoutfield";
	public static final String LAYOUTTEXT="layouttext";
	public static final String LAYOUTNAME="layoutname";
	public static final String LAYOUTWIDTH="layoutwidth";
	public static final String LAYOUTHEIGHT="layoutheight";
	public static final String LAYOUTSTYLE="layoutstyle";
	public static final String LAYOUTBLANK="layoutblank";
	public static final String LAYOUTFLDTYPE="layoutfieldtype";
	public static final String POSITION="position";
	public static final String LAYOUTX="layoutx";
	public static final String LAYOUTY="layouty";
	public static final String LAYOUTSRCFLD="layoutsrcfld";
	public static final String SRCFIELD="sourcefield";
	public static final String SRCFLDKEY="sourcefldkey";
	public static final String SRCFIELDS="sourcefields";
	public static final String SRCFLDNAME="fieldname";
	public static final String SRCFLDBEAN="fielddset";
	public static final String SRCFLDREPTYPE="fieldreptype";
	public static final String SRCFLDTYPE="fieldtype";
	public static final String SRCFLDWIDTH="fieldwidth";
	public static final String SRCFLDHEIGHT="fieldheight";
	public static final String SRCFLDSELECTED="fieldselected";
	public static final String SRCFLDEXP="fieldexp";
	public static final String SRCFLDPATTERN="fieldpattern";
	public static final String SRCFLDSORT="fieldsort";
	public static final String SRCFLDTEXT="fieldtext";
	public static final String SRCFLDGROUP="fieldgroup";
	public static final String SRCFLDOUTPUT="fieldoutput";
	public static final String STYLES="styles";
	public static final String STYLE="style";
	public static final String STYLENAME="stylename";
	public static final String STYLEFONT="stylefont";
	public static final String STYLEWEIGHT="styleweight";
	public static final String STYLESIZE="stylesize";
	public static final String STYLEITALIC="styleitalic";
	public static final String STYLEUNDERLINE="styleunderline";
	public static final String STYLESTRIKE="stylestrike";
	public static final String STYLECOLOUR="stylecolour";
	public static final String STYLEALIGN="stylealign";
	public static final String STYLEDEFAULT="styledefault";
	public static final String VARIABLES="variables";
	public static final String VARIABLE="variable";

	public void writeXML(IndentXML writer) throws XMLStreamException;
	public void loadXML(XMLEventReader xmlEventReader,XMLEvent xmlEvent,ReportTemplate template) throws XMLStreamException;
}
